apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints: {{ .Values.ingress.entryPoints }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - kind: Service
          name: {{ .Chart.Name }}
          port: 80
  tls:
    certResolver: le