apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.container.containerPort }}
  selector:
    app: {{ .Chart.Name }}
