version: '3.9'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "500m"
    max-file: "2"

services:
  {{ secrets.id }}:
    image: twobrowin/bmstu-typo-form:1.6.0
    logging: *default-logging
    networks:
      - boxed-bots-proxy
    volumes:
      - data:/pb/pb_data
    environment:
      TZ: "Europe/Moscow"
    deploy:
      replicas: 1

networks:
  boxed-bots-proxy:
    name: boxed-bots-proxy
    external: true

volumes:
  data:
