---
#############################################################################
#      0) Взять секреты из vault и добавить SSH ключи в known_hosts         #
#############################################################################

- name: Pull secrets from vault
  hosts: all
  gather_facts: false
  tags:
    - always
  roles:
    - role: bmstu.vats.init
      vault_path_secrets:
        - boxed-bots/data/bmstu-typo-form,secrets.yaml

#############################################################################
#                       1) Запуск сервиса                                   #
#############################################################################

- name: Run bot service
  hosts: managers
  tags:
    - deploy
  roles:
    - role: bmstu.vats.generic_deploy
      compose_template_path: docker-compose.j2.yaml
      stack_name:  "{{ secrets.id }}"
      stack_prune: true
      workdir:     "{{ home }}/{{ secrets.id }}"

#############################################################################
#                2) Подготовка конфигураций Nginx                           #
#############################################################################

- name: Copy nginx configs
  hosts: managers
  tags:
    - nginx_config
  tasks:
    - name: Template nginx locaions and servers
      template:
        src:  "{{ item }}"
        dest: "{{ home }}/nginx/conf.d/{{ secrets.id }}.conf.template.conf"
      with_fileglob: nginx/*.conf
    
  roles:
    - role: bmstu.vats.restart_service
      service_name: nginx
