container:
  image: twobrowin/bmstu-typo-form:1.7.0-rc0
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  dataPath: /pb/pb_data

  env:
  - name: TZ
    value: Europe/Moscow
  
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 200m
      memory: 200M

ingress:
  host: boxed-bots.ru
  entryPoints:
    - typo-web
